# Generated by Django 6.0.5 on 2026-08-26 13:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('titulo_profesional', models.CharField(max_length=100)),
                ('resumen_profesional', models.TextField(max_length=1000)),
                ('foto_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado'), ('Nativo', 'Nativo')], max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='perfil.perfil')),
            ],
            options={
                'db_table': 'idioma',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('categorias', models.ManyToManyField(blank=True, related_name='habilidades', to='certificados.categoria')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='perfil.perfil')),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('actual', models.BooleanField(default=False)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='perfil.perfil')),
            ],
            options={
                'db_table': 'experiencia',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='perfil.perfil')),
            ],
            options={
                'db_table': 'educacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['usuario'], name='idx_perfil_usuario'),
        ),
        migrations.AddConstraint(
            model_name='habilidad',
            constraint=models.UniqueConstraint(fields=('perfil', 'nombre'), name='unique_habilidad_perfil'),
        ),
        migrations.AddIndex(
            model_name='experiencia',
            index=models.Index(fields=['perfil'], name='idx_experiencia_perfil'),
        ),
    ]
