# Generated by Django 6.0.5 on 2026-08-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_educacion_created_at_educacion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidad',
            name='tipo',
            field=models.CharField(choices=[('hard', 'Hard Skills'), ('power', 'Power Skills')], default='hard', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
