# Generated by Django 6.0.5 on 2026-08-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_habilidad_tipo_perfil_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
