# Generated by Django 6.0.5 on 2026-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_idioma_nivel_cefr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nivel',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1'), ('C2', 'C2')], max_length=20),
        ),
    ]
