# Generated by Django 6.0.5 on 2026-08-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificados', '0001_initial'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='perfil.perfil'),
        ),
        migrations.AddConstraint(
            model_name='categoria',
            constraint=models.UniqueConstraint(fields=('usuario', 'nombre'), name='unique_categoria_usuario'),
        ),
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['perfil'], name='idx_certificado_perfil'),
        ),
    ]
