# Generated by Django 6.0.5 on 2026-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
