# Generated by Django 6.0.5 on 2026-08-31 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_categoria_is_active_categoria_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['-fecha_obtencion']},
        ),
    ]
